name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --label "org.opencontainers.image.revision=${GITHUB_SHA}" --tag ghcr.io/jt-nti/lametric-cheerlights:${GITHUB_SHA}
    - name: Publish Docker image
      if: github.event_name != 'pull_request'
      run: |
        echo ${DOCKER_PW} | docker login ghcr.io -u ${DOCKER_USER} --password-stdin
        docker push ghcr.io/jt-nti/lametric-cheerlights:${GITHUB_SHA}
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_PW: ${{ secrets.GITHUB_TOKEN }}
